gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      project: Rover
      projectid: rover
      developer: SenorContento
      description: This is a blog written by Brandon Gomez to talk about Rover!
      site-url: https://rover.senorcontento.com
      rss-url: https://rover.senorcontento.com/blog/atom.xml
      branch: gh-pages
      image: /sitedata/images/favicon.png



paginate_path: "/blog/page:num/"
paginate: 5
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
